config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:session], :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"
  }

  as :user do 
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end
   as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :user_friendships do
    member do
      put :accept
    end
  end

  resources :users do
    member do
      get :following, :followers
      patch :state_facebook
      patch :state_twitter
    end
  end

resources :relationships, only: [:create, :destroy]

resources :statuses do
  member do
      put "like", to: "statuses#upvote"
      put "unlike", to: "statuses#downvote"
  end
  resources :comments
end

  resources :statuses
  get 'feeds', to: 'statuses#index', as: :feeds
  get "post_video", to: "statuses#create_post_video"

  resources :educational_details

  resources :a_brief_about_yourselves
  resources :work_experiences
  resources :notifications
  resources :messages

  root to: 'welcome#index'

  get '/:id', to: 'profiles#show', as: 'profile'
  get 'edit_profile/:id', to: 'profiles#edit', as: 'edit_profile'
  get 'profiles/users', to: 'profiles#index', as: :profiles_users

  resources :profiles do
    put :profile_params
  end

  resources :conversations do
    resources :messages
  end

  namespace :api do
    namespace :v1 do
      get '/:profile_name/interests', to: "interests#index"
    end
  end
  
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_status, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  
  # GET /statuses
  # GET /statuses.json
  def index
    ids = current_user.friends.pluck(:id) << current_user.id
    @statuses_all = Status.where(user_id: ids).order(id: :desc)
    @status = Status.new

    @statuses = current_user.statuses.all

    @users = current_user.friends
    @user = current_user

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create_post_video
    @status = Status.new
  end


  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(status_params)

    if current_user.state_facebook? && @status.content?
      current_user.facebook(current_user).put_wall_post(@status.content)
    end

    if current_user.state_twitter? && @status.content?
      current_user.twitter(current_user).update(@status.content)
    end
    
    respond_to do |format|
      if @status.save
        format.html { redirect_to statuses_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { redirect_to statuses_url }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update

    #LA
    #@status = current_user.statuses.find(status_params)

    #if (status_params) && (status_params).has_key?(:user_id)
    #  (status_params).delete(:user_id) 
    #end

    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to statuses_url, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end


  def upvote
    @status = Status.find(params[:id])
    @status.liked_by current_user
    @path = status_path(@status)
    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render :layout => false }
    end
  end

  def downvote
    @status.downvote_from current_user
    redirect_to statuses_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:user_id, :content, :image, :video)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
	def broadcast(channel, &block)
	  message = {:channel => channel, :data => capture(&block)}
	  uri = URI.parse("http://localhost:9292/faye")
	  Net::HTTP.post_form(uri, :status => message.to_json)
	end
end

app/views/statuses/_form_image.html.erb
<%= form_for(@status, html: {multipart: true}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

     <div class="box-post">
      <div class="media-left media-top">
      </div>
      <div class="media-body">
         <div class="form-group">
          <%= f.text_area :content , class: 'form-text-area', row: "2", placeholder: "Start posting here..." %>
         </div>
      </div>
    </div>
  
    <div class="pull-right"> 
      <%= button_tag(type: "submit", name: nil, class: "btn btn-primary dropdown-toggle" , data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Loading..." } ) do %>
            <strong>Post</strong>
        <% end %>
    </div>

    <%= f.file_field :image , title: "Add New Image" %>

<% end %>

app/views/statuses/_form_video.html.erb
<%= form_for(@status, html: {multipart: true}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

     <div class="box-post">
      <div class="media-left media-top">
      </div>
      <div class="media-body">
         <div class="form-group">
          <%= f.text_area :content , class: 'form-text-area', row: "2", placeholder: "Start posting here..." %>
         </div>
      </div>
    </div>

    <%= f.file_field :video , title: "Add New Video"%>
  
    <div class="pull-right"> 
      <%= button_tag(type: "submit", name: nil, class: "btn btn-primary dropdown-toggle" , data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Loading..." } ) do %>
            <strong>Post</strong>
        <% end %>
    </div>

    

<% end %>

app/views/statuses/_link_comment.html.erb
<% if @status.comments.count > 0 %>
	<%= link_to new_status_comment_path(@status), :remote => true, :id => "new_comment-#{status.id}" do %>
    <p style="font-size:13px; color:#9e9e9e"><i class="fa fa-plus"></i> Add a comment... </p>
    <% end %>
<% else %>
    <%= link_to new_status_comment_path(@status), :remote => true, :id => "new_comment-#{status.id}" do %>
    <p style="font-size:13px; color:#9e9e9e"><i class="fa fa-plus"></i> Be the first one to comment</p>
    <% end %>
<% end %>

app/views/statuses/_options.html.erb
<a aria-expanded="false" href="#" class="dropdown-toggle dimmed" data-toggle="dropdown">
  <i class="fa fa-ellipsis-h"><span class="text-hide">Options</span></i>
</a>
<ul class="dropdown-menu">
  <li>
    <%= link_to edit_status_path(status), remote: true do %>
      <i class="fa fa-edit"></i> Edit
    <% end %>
  </li>
  <li class="divider"></li>
  <li>
    <%= link_to status, method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
      <i class="fa fa-trash-o"></i> Delete
    <% end %>
  </li>
</ul>

app/views/statuses/_profile_info.html.erb
<div class="col-md-1 col-xl-1" style="margin-left:1px; margin-top: 20px;" >
          <%= avatar_profile_link @user, "thumb", class: 'img-circle'%>

</div>
<div class="profinfo">
        <p style="font-size:14px; color:#232323"><b><%= @user.full_name.upcase %></b></p>
        <p style="font-size:13px; color:#9f9f9f"> </p>
        <% if current_user.id == @user.id %>
        	<p style="font-size:13px; color:#cfcfcf"><%= link_to "Edit Profile", edit_profile_path(@user) %></p>
    	<% end %>
</div>

app/views/statuses/_recommendations.html.erb
 <p style="font-size:15px; color:#232323; margin-top:50px;"><b>YOUR TOP RECOMMENDATIONS</b></p>
    <div class="panel panel-default">
      <div class="panel-body">
        <p style="font-size:14px color:"><b>Best Laptops you wanna buy</b></p>
        <p style="font-size:13px; color:#909090"><b>Yesterday 15:21</b></p>
        <p style="font-size:13px; color:#3e3e3e;"><b>You are looking for the best laptops and here we list out few based on the recommendations. <a href="#" style="color:#8f8f8f">Read More</a></b></p>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-body">
        <p style="font-size:14px color:"><b>Best Laptops you wanna buy</b></p>
        <p style="font-size:13px; color:#909090"><b>Yesterday 5:30</b></p>
        <%= image_tag 'Laptop1.jpg',  class: "img-responsive", width: "250px", height: "200px"%>
        <p style="font-size:13px; color:#3e3e3e;"><b>You are looking for the best laptops and here we list out few based on the recommendations. <a href="#" style="color:#8f8f8f">Read More</a></b></p>

      </div>
    </div>

app/views/statuses/_status.html.erb
<div class="panel panel-default" id="post_<%= status.id %>">
  <div class="panel-body" >
    <div id="status_edit-<%= status.id %>" style="display:none;"></div>
          <div class="row">
            <div class="col-md-3 col-xl-1">
               <%= avatar_profile_link status.user, "thumb", class: 'img-avatar' %>
            </div>
            <div class="col-md-4">
              <p style="font-size:14px; color:#232323"><b> <%= status.user.full_name %></b></p>
              <p id="statlink" style="font-size:12px; color:#909090"><b> <%= link_to time_ago_in_words(status.created_at) + " ago", status %></b></p>
            </div>
            <div class="col-md-3 col-xl-1">
               <%= avatar_profile_link status.user, "thumb", class: 'img-avatar' %>
            </div>
            <div class="col-lg-1 options">
                <div class="btn-group status-options">
                  <% if current_user && status.user == current_user %>
                  <%= render partial: 'statuses/options', locals: { status: status } %>
                  <% end %>
                </div>
              </div>
            </div>
          <br>
          <div class="row">
           
            <p style="font-size:13px; color:#3e3e3e; padding-left:20px; padding-right:20px;"><b><%= status.content %></b></p>
            <% if status.image_file_name != nil %>
              <%= image_tag status.image.url(:thumb) %>
            <% end %>
            <% if status.video_file_name != nil %>
              <%= video_tag status.video.url(:medium), controls: true, style: "max-width: 100%;", size: "455x300"%>
            <% end %>
         </div>

          <div class="row">
            <div class="col-md-6 pull-left">           
              <% if status.get_upvotes.size == 0 %>  
                <% @users.each do |user| %>
                  <% if user == status.user%>
                    <%= link_to like_status_path(status), remote: true, method: :put, class: 'vpos'   do %>
                     <p style="font-size:15px; color:#9e9e9e;"><span class="button-<%= status.id %>"><i class="fa fa-heart-o "></i></span>
                      <span class="vcount-<%= status.id %>"><%= status.get_upvotes.size %> likes</span>
                     </p>
                    <% end %>
                  <% end %>
                <% end %>
                <% if current_user == status.user %>
                  <%= link_to like_status_path(status), remote: true, method: :put, class: 'vpos'   do %>
                     <p style="font-size:15px; color:#9e9e9e;"><span class="button-<%= status.id %>"><i class="fa fa-heart-o "></i></span>
                      <span class="vcount-<%= status.id %>"><%= status.get_upvotes.size %> likes</span>
                     </p>
                    <% end %>
                <% end %>

              <% else %> 
                <% @users.each do |user| %>
                  <% if user == status.user%>
                     <%= link_to like_status_path(status), remote: true, method: :put, class: 'vpos'   do %>
                     <p style="font-size:15px; color:#9e9e9e;"><span class="button-<%= status.id %>"><i class="fa fa-heart-o blackiconcolor"></i></span>
                      <span class="vcount-<%= status.id %>"><%= status.get_upvotes.size %> likes</span>
                     </p>
                     <% end %>
                  <% end %>
                <% end %>
                <% if current_user == status.user %>
                    <%= link_to like_status_path(status), remote: true, method: :put, class: 'vpos'   do %>
                     <p style="font-size:15px; color:#9e9e9e;"><span class="button-<%= status.id %>"><i class="fa fa-heart-o blackiconcolor"></i></span>
                      <span class="vcount-<%= status.id %>"><%= status.get_upvotes.size %> likes</span>
                     </p>
                     <% end %>
                <% end %>

              <% end %>
            </div>
          </div>     
          </div>
        <div class="panel-footer">
          <% @users.each do |user| %>
            <% if user == status.user%>
              <%= render :partial => 'comments/index', object: status, as: "status" %>
            <% end %>
          <% end %>
          <% if current_user == status.user %>
            <%= render :partial => 'comments/index', object: status, as: "status" %>
          <% end %>
        </div>
</div>
 <% if status.user_id == current_user.id %>
<%= subscribe_to status_path(status) %>
<% end %>

<%= subscribe_to user_friendships_path(@user_friendships) %>

app/views/statuses/create_post_video.js.erb
$('#status-form').html("<%= j (render 'form_video') %>");
$('#status-form').slideDown(350);
$('#render-form').slideUp(100);

app/views/statuses/destroy.js.erb
$('#post_<%= @status.id %>').remove();

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.js.erb
$('#status-form').html("<%= j (render 'form_image') %>");
$('#status-form').slideDown(350);
$('#render-form').slideUp(100);

app/views/statuses/new.js.erb
$('#status-form').html("<%= j (render 'form') %>");
$('#status-form').slideDown(350);
$('#render-form').slideUp(100);

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @status.user.full_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>
<h2>****COMMENTS****</h2>
		<h2>Add a comment:</h2>
		
		
 	</div>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/upvote.js.erb
$('.vpos').bind('ajax:success', function() {
$('.vcount-<%= @status.id %>').html('<%= escape_javascript @status.get_upvotes.size.to_s %> likes');
$('.button-<%= @status.id %>').addClass( "blackiconcolor" );
<% publish_to @path do %>
	<% if @status.get_upvotes.last.voter.id != @status.user_id %>
		$('#icon-noti').addClass('new');
	<% end %>
<% end %>

});