config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:session], :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"
  }

  as :user do 
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end
   as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :user_friendships do
    member do
      put :accept
    end
  end

  resources :users do
    member do
      get :following, :followers
      patch :state_facebook
      patch :state_twitter
    end
  end

resources :relationships, only: [:create, :destroy]

resources :statuses do
  member do
      put "like", to: "statuses#upvote"
      put "unlike", to: "statuses#downvote"
  end
  resources :comments
end

  resources :statuses
  get 'feeds', to: 'statuses#index', as: :feeds
  get "post_video", to: "statuses#create_post_video"

  resources :educational_details

  resources :a_brief_about_yourselves
  resources :work_experiences
  resources :notifications
  resources :messages

  root to: 'welcome#index'

  get '/:id', to: 'profiles#show', as: 'profile'
  get 'edit_profile/:id', to: 'profiles#edit', as: 'edit_profile'
  get 'profiles/users', to: 'profiles#index', as: :profiles_users

  resources :profiles do
    put :profile_params
  end

  resources :conversations do
    resources :messages
  end

  namespace :api do
    namespace :v1 do
      get '/:profile_name/interests', to: "interests#index"
    end
  end
  
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  end

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end

  def with_hibot?
    hibot_id = User.find_by_profile_name("hibot").id
    recipient_id == hibot_id
  end  
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!

  layout false

  def index
    
  end

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id],params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end

    render json: { conversation_id: @conversation.id }
  end

  def show
    @conversation = Conversation.find(params[:id])
    @reciever = interlocutor(@conversation)
    @messages = @conversation.messages
    @message = Message.new
    @users = current_user.friends
  end

  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

  def interlocutor(conversation)
    current_user == conversation.recipient ? conversation.sender : conversation.recipient
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<div style="height: 400px; overflow-y: auto;">
      <% if not(@conversations.nil?) and @conversations.any? %>
          <ul class="media-list">
            <% @conversations.each do |conversation| %>
                <% 
                  if conversation.sender_id == current_user.id
                    sender = User.find conversation.recipient_id
                  else 
                    sender = User.find conversation.sender_id
                  end
                %>
                <li class="media">
                  <%= avatar_profile_link sender, "thumb",class: "img-avatar-noti btn-xs start-conversation" %>
                  <div class="media-body">
                    <%= link_to conversation_path(conversation), class: "conversation", "data-cid" => conversation.id do %>
                        <p style="font-size:14px; color:#232323"><%= conversation_interlocutor(conversation).full_name %></p>
                        <p style="font-size:14px; color:#232323"><%= conversation.messages.last.nil? ? "No messages" : truncate(conversation.messages.last.body, length: 45) %></p>
                    <% end %>
                  </div>
                </li>

            <% end %>
          </ul>
          <div >
            <center><%= link_to "View all",  messages_path , class: "btn btn-info dropdown-toggle"%></center>
          </div>
      <% else %>
          <p>You have no conversations. Click send message with any user to create one.</p>
      <% end %>   
</div>

app/views/conversations/show.html.erb
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>

    <h1><%= @reciever.full_name %> </h1>
  </div>
  <div class="chatboxoptions">
    <%= link_to "<i class='fa  fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='fa  fa-times'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<div class="chatboxinput">
  <%= form_for([@conversation, @message], :remote => true, :html => { id: "conversation_form_#{@conversation.id}"}) do |f| %>
      <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @conversation.id %>
  <% end %>
</div>

<%= subscribe_to conversation_path(@conversation) %>