config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:session], :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"
  }

  as :user do 
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end
   as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :user_friendships do
    member do
      put :accept
    end
  end

  resources :users do
    member do
      get :following, :followers
      patch :state_facebook
      patch :state_twitter
    end
  end

resources :relationships, only: [:create, :destroy]

resources :statuses do
  member do
      put "like", to: "statuses#upvote"
      put "unlike", to: "statuses#downvote"
  end
  resources :comments
end

  resources :statuses
  get 'feeds', to: 'statuses#index', as: :feeds
  get "post_video", to: "statuses#create_post_video"

  resources :educational_details

  resources :a_brief_about_yourselves
  resources :work_experiences
  resources :notifications
  resources :messages

  root to: 'welcome#index'

  get '/:id', to: 'profiles#show', as: 'profile'
  get 'edit_profile/:id', to: 'profiles#edit', as: 'edit_profile'
  get 'profiles/users', to: 'profiles#index', as: :profiles_users

  resources :profiles do
    put :profile_params
  end

  resources :conversations do
    resources :messages
  end

  namespace :api do
    namespace :v1 do
      get '/:profile_name/interests', to: "interests#index"
    end
  end
  
end

app/models/work_experience.rb
class WorkExperience < ActiveRecord::Base
	belongs_to :user

	validates :companyName, presence: true
	validates :designation, presence: true
	validates :location, presence: true

end

app/controllers/work_experiences_controller.rb
class WorkExperiencesController < ApplicationController
  before_action :set_work_experience, only: [:show, :edit, :update, :destroy]

  # GET /work_experiences
  # GET /work_experiences.json
  def index
    @work_experiences = WorkExperience.all
  end

  # GET /work_experiences/1
  # GET /work_experiences/1.json
  def show
  end

  # GET /work_experiences/new
  def new
    @work_experience = WorkExperience.new
  end

  # GET /work_experiences/1/edit
  def edit
  end

  # POST /work_experiences
  # POST /work_experiences.json
  def create
    if current_user.work_experience.nil?
      @work_experience = current_user.create_work_experience(work_experience_params)

      respond_to do |format|
        if @work_experience.save
          format.html { redirect_to statuses_url, notice: 'Work experience was successfully created.' }
          format.json { render :show, status: :created, location: @work_experience }
        else
          format.html { redirect_to edit_profile_url(current_user), alert: 'Work experience was not created'}
          format.json { render json: @work_experience.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to edit_profile_url(current_user)
      flash[:alert] = 'Already exists Work experience'
    end
  end

  # PATCH/PUT /work_experiences/1
  # PATCH/PUT /work_experiences/1.json
  def update
    respond_to do |format|
      if @work_experience.update(work_experience_params)
        format.html { redirect_to @work_experience, notice: 'Work experience was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_experience }
      else
        format.html { render :edit }
        format.json { render json: @work_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_experiences/1
  # DELETE /work_experiences/1.json
  def destroy
    @work_experience.destroy
    respond_to do |format|
      format.html { redirect_to work_experiences_url, notice: 'Work experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_experience
      @work_experience = WorkExperience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_experience_params
      params.require(:work_experience).permit(:companyName, :designation, :location)
    end
end

app/helpers/work_experiences_helper.rb
module WorkExperiencesHelper
end

app/views/work_experiences/_form.html.erb
<%= form_for(@work_experience) do |f| %>
  <% if @work_experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_experience.errors.count, "error") %> prohibited this work_experience from being saved:</h2>

      <ul>
      <% @work_experience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h4>Work Experience</h4>
  <div class="row">
    <div class="col-xs-6 col-md-6"> <%= f.text_field :companyName , class: 'form-control', placeholder: "Company Name"%></div>
    <div class="col-xs-6 col-md-6"> <%= f.text_field :designation , class: 'form-control', placeholder: "Designation"%></div>
  </div>

  <br>

  <div class="row">
    <div class="col-xs-6 col-md-6">
      <%= f.text_field :location , class: 'form-control', placeholder: "Location"%>
    </div>
  </div>
  <br>
  <div class="actions">
    <%= button_tag(type: "submit", class: "btn btn-info dropdown-toggle") do %>
    Save Details  
    <% end %>
  </div>
<% end %>

app/views/work_experiences/edit.html.erb
<h1>Editing Work Experience</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_experience %> |
<%= link_to 'Back', work_experiences_path %>

app/views/work_experiences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Work Experiences</h1>

<table>
  <thead>
    <tr>
      <th>Companyname</th>
      <th>Designation</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_experiences.each do |work_experience| %>
      <tr>
        <td><%= work_experience.companyName %></td>
        <td><%= work_experience.designation %></td>
        <td><%= work_experience.location %></td>
        <td><%= link_to 'Show', work_experience %></td>
        <td><%= link_to 'Edit', edit_work_experience_path(work_experience) %></td>
        <td><%= link_to 'Destroy', work_experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work experience', new_work_experience_path %>

app/views/work_experiences/new.html.erb
<h1>New Work Experience</h1>

<%= render 'form' %>

<%= link_to 'Back', work_experiences_path %>

app/views/work_experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Companyname:</strong>
  <%= @work_experience.companyName %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @work_experience.designation %>
</p>

<p>
  <strong>Location:</strong>
  <%= @work_experience.location %>
</p>

<%= link_to 'Edit', edit_work_experience_path(@work_experience) %> |
<%= link_to 'Back', work_experiences_path %>